
import * as d from './components';

export const DIRECTIVES = [
  d.VeriteConnector,
  d.VuiAuthAltCard,
  d.VuiAuthCard,
  d.VuiAuthFooter,
  d.VuiAuthForm,
  d.VuiAuthHeader,
  d.VuiBrand,
  d.VuiButton,
  d.VuiCard,
  d.VuiCardContent,
  d.VuiCardDescription,
  d.VuiCardFooter,
  d.VuiCardHeader,
  d.VuiCardTitle,
  d.VuiDivider,
  d.VuiDropdownMenu,
  d.VuiDropdownMenuContent,
  d.VuiDropdownMenuItem,
  d.VuiDropdownMenuSeparator,
  d.VuiDropdownMenuTrigger,
  d.VuiErrorMessage,
  d.VuiFlex,
  d.VuiFormInput,
  d.VuiGoogleOneTap,
  d.VuiI18n,
  d.VuiI18nProvider,
  d.VuiIcon,
  d.VuiLabel,
  d.VuiLanguageSwitcher,
  d.VuiLink,
  d.VuiLogo,
  d.VuiOtp,
  d.VuiPlaceholder,
  d.VuiRequest,
  d.VuiSpinner,
  d.VuiTextbox,
  d.VuiThemeToggle,
  d.VuiToast,
  d.VuiUserMenu
];
