/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Element } from "@stencil/core";
import { EmailValidationOptions, PasswordValidationOptions } from "./utils/validation";
import { SignUpFormData } from "./components/auth/types";
import { SignInWithIdTokenCredentials } from "./components/google-one-tap/google-one-tap-interfaces";
import { Translation } from "./components/i18n/i18n-provider";
import { Language } from "./components/i18n/language-switcher";
import { LogoName } from "./components/logo/logo";
import { ToastProps, ToastType } from "./components/toast/toast-interfaces";
import { MenuAction } from "./components/user-menu/user-menu-interfaces";
export { Element } from "@stencil/core";
export { EmailValidationOptions, PasswordValidationOptions } from "./utils/validation";
export { SignUpFormData } from "./components/auth/types";
export { SignInWithIdTokenCredentials } from "./components/google-one-tap/google-one-tap-interfaces";
export { Translation } from "./components/i18n/i18n-provider";
export { Language } from "./components/i18n/language-switcher";
export { LogoName } from "./components/logo/logo";
export { ToastProps, ToastType } from "./components/toast/toast-interfaces";
export { MenuAction } from "./components/user-menu/user-menu-interfaces";
export namespace Components {
    interface VeriteConnector {
        "type": 'signup' | 'signin';
    }
    interface VuiAuthAltCard {
        "action": string;
        "description": string;
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
        "heading": string;
        "prompt": string;
        "submitLabel": string;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthCard {
        "action": string;
        "brandLabel"?: string;
        "brandLogo"?: string;
        "description": string;
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
        "heading": string;
        "prompt": string;
        "submitLabel": string;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthFooter {
        "action"?: string;
        "brandLabel"?: string;
        "brandLogo"?: string;
        "prompt"?: string;
        "showBrand"?: boolean;
        "showDivider"?: boolean;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthForm {
        "action": 'submit' | 'signup' | 'signin' | 'forgotPassword' | 'resetPassword' | 'resetLink' | 'code';
        "elements"?: Element[] | string;
        "email"?: string;
        "emailLabel": string;
        "emailPlaceholder": string;
        /**
          * Email validation options
         */
        "emailValidation"?: EmailValidationOptions | string;
        "firstName"?: string;
        "firstnameLabel": string;
        "firstnamePlaceholder": string;
        "forgotPasswordLabel": string;
        /**
          * Controls the loading state of the component
         */
        "isLoading"?: boolean;
        "lastName"?: string;
        "lastnameLabel": string;
        "lastnamePlaceholder": string;
        "password"?: string;
        "passwordHideLabel": string;
        "passwordLabel": string;
        "passwordPlaceholder": string;
        "passwordShowLabel": string;
        /**
          * Password validation options
         */
        "passwordValidation"?: PasswordValidationOptions;
        "phone"?: string;
        "phoneLabel": string;
        "phonePlaceholder": string;
        "styles"?: {
    link?: { [key: string]: string | number }
  };
        "submitLabel": string;
    }
    interface VuiAuthHeader {
        "align": 'start' | 'center' | 'end';
        "description": string;
        "heading": string;
        "size": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VuiBrand {
        "label": string;
        "logo": string;
    }
    interface VuiButton {
        "busy"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "name"?: string;
        "size"?: 'default' | 'sm' | 'lg' | 'icon';
        "type": 'button' | 'submit' | 'reset';
        "value"?: string;
        "variant"?: 'default' | 'soft' | 'outline' | 'ghost' | 'destructive';
        "width"?: 'full' | 'auto';
    }
    interface VuiCard {
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VuiCardContent {
    }
    interface VuiCardDescription {
        "align": 'start' | 'center' | 'end';
    }
    interface VuiCardFooter {
        "variant": 'default' | 'inset';
    }
    interface VuiCardHeader {
    }
    interface VuiCardTitle {
        "align": 'start' | 'center' | 'end';
        "size": 'sm' | 'md' | 'lg' | 'xl';
        "weight": 'bold' | 'medium' | 'light';
    }
    interface VuiDivider {
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface VuiDropdownMenu {
        "position": 'bottom-end' | 'bottom-start' | 'top-end' | 'top-start';
    }
    interface VuiDropdownMenuContent {
    }
    interface VuiDropdownMenuItem {
        "disabled"?: boolean;
    }
    interface VuiDropdownMenuSeparator {
    }
    interface VuiDropdownMenuTrigger {
    }
    interface VuiErrorMessage {
        /**
          * The error message to display
         */
        "message": string;
        /**
          * Whether to show the error icon
         */
        "showIcon": boolean;
    }
    interface VuiFlex {
        "breakpoint"?: string;
        "breakpointDirection"?: 'row' | 'column';
        "direction"?: 'row' | 'column';
        "gap"?: number;
        "grow"?: boolean;
        "items"?: 'start' | 'center' | 'end' | 'stretch' | 'baseline';
        "justify"?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
        "spaceUnit"?: number;
        "width"?: 'full' | 'auto';
        "wrap"?: 'nowrap' | 'wrap' | 'wrap-reverse';
    }
    interface VuiFormInput {
        "errorMessage"?: string;
        "htmlFor": string;
        "label": string;
    }
    interface VuiGoogleOneTap {
        "googleClientId": string;
    }
    interface VuiI18n {
        "params"?: Record<string, string> | string;
        "text": string;
    }
    interface VuiI18nProvider {
        "fallbackLocale"?: string;
        "loadTranslations"?: (locale: string) => Promise<Translation>;
        "locale": string;
        "translations"?: Translation | string;
        "translationsPath"?: string;
    }
    interface VuiIcon {
        "color"?: string;
        "name": string;
        "size"?: 'xs' | 'sm' | 'md' | 'lg';
    }
    interface VuiLabel {
        "for"?: string;
        "required"?: boolean;
    }
    interface VuiLanguageSwitcher {
        "currentLocale"?: string;
        "languages": Language[] | string;
        "variant": 'select' | 'buttons';
    }
    interface VuiLink {
        "disabled"?: boolean;
        "href"?: string;
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        "variant"?: 'default' | 'muted' | 'destructive';
    }
    interface VuiLogo {
        /**
          * The name of the logo to display
         */
        "name": LogoName;
        /**
          * The size of the logo in pixels
         */
        "size": number;
    }
    interface VuiOtp {
        "submitLabel"?: string;
    }
    interface VuiPlaceholder {
        /**
          * Height of the placeholder in pixels
         */
        "height": number;
        /**
          * Border radius in pixels. Use 9999 for fully rounded
         */
        "radius": number;
        /**
          * Width of the placeholder in pixels
         */
        "width": number;
    }
    interface VuiRequest {
        "application"?: string;
        "isLoading"?: boolean;
        "permissions"?: string[] | string;
        "redirectUri"?: string;
        "showRedirect"?: boolean;
    }
    interface VuiSpinner {
        "color": string;
        "size": 'small' | 'medium' | 'large';
    }
    interface VuiTextbox {
        "autocomplete"?: string;
        "autocorrect"?: 'on' | 'off';
        "disabled"?: boolean;
        "focusable"?: boolean;
        "maxlength"?: number;
        "name"?: string;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "type": string;
        "value": string;
    }
    interface VuiThemeToggle {
    }
    interface VuiToast {
        "dismissToast": (id: string) => Promise<void>;
        "duration": number;
        "gap": number;
        "position": 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
        /**
          * Shows a new toast notification
          * @param toast - Toast properties without ID
          * @returns Generated toast ID
         */
        "show": (toast: Omit<ToastProps, 'id'>) => Promise<string>;
        "theme": 'default' | 'light' | 'dark' | 'inverted';
        "update": (id: string, toast: Partial<ToastProps>) => Promise<void>;
    }
    interface VuiUserMenu {
    }
}
export interface VuiAuthFooterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiAuthFooterElement;
}
export interface VuiAuthFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiAuthFormElement;
}
export interface VuiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiButtonElement;
}
export interface VuiDropdownMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiDropdownMenuItemElement;
}
export interface VuiGoogleOneTapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiGoogleOneTapElement;
}
export interface VuiI18nProviderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiI18nProviderElement;
}
export interface VuiLanguageSwitcherCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiLanguageSwitcherElement;
}
export interface VuiOtpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiOtpElement;
}
export interface VuiRequestCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiRequestElement;
}
export interface VuiTextboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiTextboxElement;
}
export interface VuiToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiToastElement;
}
export interface VuiUserMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVuiUserMenuElement;
}
declare global {
    interface HTMLVeriteConnectorElement extends Components.VeriteConnector, HTMLStencilElement {
    }
    var HTMLVeriteConnectorElement: {
        prototype: HTMLVeriteConnectorElement;
        new (): HTMLVeriteConnectorElement;
    };
    interface HTMLVuiAuthAltCardElement extends Components.VuiAuthAltCard, HTMLStencilElement {
    }
    var HTMLVuiAuthAltCardElement: {
        prototype: HTMLVuiAuthAltCardElement;
        new (): HTMLVuiAuthAltCardElement;
    };
    interface HTMLVuiAuthCardElement extends Components.VuiAuthCard, HTMLStencilElement {
    }
    var HTMLVuiAuthCardElement: {
        prototype: HTMLVuiAuthCardElement;
        new (): HTMLVuiAuthCardElement;
    };
    interface HTMLVuiAuthFooterElementEventMap {
        "actionClick": any;
    }
    interface HTMLVuiAuthFooterElement extends Components.VuiAuthFooter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiAuthFooterElementEventMap>(type: K, listener: (this: HTMLVuiAuthFooterElement, ev: VuiAuthFooterCustomEvent<HTMLVuiAuthFooterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiAuthFooterElementEventMap>(type: K, listener: (this: HTMLVuiAuthFooterElement, ev: VuiAuthFooterCustomEvent<HTMLVuiAuthFooterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiAuthFooterElement: {
        prototype: HTMLVuiAuthFooterElement;
        new (): HTMLVuiAuthFooterElement;
    };
    interface HTMLVuiAuthFormElementEventMap {
        "formSubmit": SignUpFormData;
        "forgotPassword": void;
    }
    interface HTMLVuiAuthFormElement extends Components.VuiAuthForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiAuthFormElementEventMap>(type: K, listener: (this: HTMLVuiAuthFormElement, ev: VuiAuthFormCustomEvent<HTMLVuiAuthFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiAuthFormElementEventMap>(type: K, listener: (this: HTMLVuiAuthFormElement, ev: VuiAuthFormCustomEvent<HTMLVuiAuthFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiAuthFormElement: {
        prototype: HTMLVuiAuthFormElement;
        new (): HTMLVuiAuthFormElement;
    };
    interface HTMLVuiAuthHeaderElement extends Components.VuiAuthHeader, HTMLStencilElement {
    }
    var HTMLVuiAuthHeaderElement: {
        prototype: HTMLVuiAuthHeaderElement;
        new (): HTMLVuiAuthHeaderElement;
    };
    interface HTMLVuiBrandElement extends Components.VuiBrand, HTMLStencilElement {
    }
    var HTMLVuiBrandElement: {
        prototype: HTMLVuiBrandElement;
        new (): HTMLVuiBrandElement;
    };
    interface HTMLVuiButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLVuiButtonElement extends Components.VuiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiButtonElementEventMap>(type: K, listener: (this: HTMLVuiButtonElement, ev: VuiButtonCustomEvent<HTMLVuiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiButtonElementEventMap>(type: K, listener: (this: HTMLVuiButtonElement, ev: VuiButtonCustomEvent<HTMLVuiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiButtonElement: {
        prototype: HTMLVuiButtonElement;
        new (): HTMLVuiButtonElement;
    };
    interface HTMLVuiCardElement extends Components.VuiCard, HTMLStencilElement {
    }
    var HTMLVuiCardElement: {
        prototype: HTMLVuiCardElement;
        new (): HTMLVuiCardElement;
    };
    interface HTMLVuiCardContentElement extends Components.VuiCardContent, HTMLStencilElement {
    }
    var HTMLVuiCardContentElement: {
        prototype: HTMLVuiCardContentElement;
        new (): HTMLVuiCardContentElement;
    };
    interface HTMLVuiCardDescriptionElement extends Components.VuiCardDescription, HTMLStencilElement {
    }
    var HTMLVuiCardDescriptionElement: {
        prototype: HTMLVuiCardDescriptionElement;
        new (): HTMLVuiCardDescriptionElement;
    };
    interface HTMLVuiCardFooterElement extends Components.VuiCardFooter, HTMLStencilElement {
    }
    var HTMLVuiCardFooterElement: {
        prototype: HTMLVuiCardFooterElement;
        new (): HTMLVuiCardFooterElement;
    };
    interface HTMLVuiCardHeaderElement extends Components.VuiCardHeader, HTMLStencilElement {
    }
    var HTMLVuiCardHeaderElement: {
        prototype: HTMLVuiCardHeaderElement;
        new (): HTMLVuiCardHeaderElement;
    };
    interface HTMLVuiCardTitleElement extends Components.VuiCardTitle, HTMLStencilElement {
    }
    var HTMLVuiCardTitleElement: {
        prototype: HTMLVuiCardTitleElement;
        new (): HTMLVuiCardTitleElement;
    };
    interface HTMLVuiDividerElement extends Components.VuiDivider, HTMLStencilElement {
    }
    var HTMLVuiDividerElement: {
        prototype: HTMLVuiDividerElement;
        new (): HTMLVuiDividerElement;
    };
    interface HTMLVuiDropdownMenuElement extends Components.VuiDropdownMenu, HTMLStencilElement {
    }
    var HTMLVuiDropdownMenuElement: {
        prototype: HTMLVuiDropdownMenuElement;
        new (): HTMLVuiDropdownMenuElement;
    };
    interface HTMLVuiDropdownMenuContentElement extends Components.VuiDropdownMenuContent, HTMLStencilElement {
    }
    var HTMLVuiDropdownMenuContentElement: {
        prototype: HTMLVuiDropdownMenuContentElement;
        new (): HTMLVuiDropdownMenuContentElement;
    };
    interface HTMLVuiDropdownMenuItemElementEventMap {
        "itemClick": void;
    }
    interface HTMLVuiDropdownMenuItemElement extends Components.VuiDropdownMenuItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiDropdownMenuItemElementEventMap>(type: K, listener: (this: HTMLVuiDropdownMenuItemElement, ev: VuiDropdownMenuItemCustomEvent<HTMLVuiDropdownMenuItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiDropdownMenuItemElementEventMap>(type: K, listener: (this: HTMLVuiDropdownMenuItemElement, ev: VuiDropdownMenuItemCustomEvent<HTMLVuiDropdownMenuItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiDropdownMenuItemElement: {
        prototype: HTMLVuiDropdownMenuItemElement;
        new (): HTMLVuiDropdownMenuItemElement;
    };
    interface HTMLVuiDropdownMenuSeparatorElement extends Components.VuiDropdownMenuSeparator, HTMLStencilElement {
    }
    var HTMLVuiDropdownMenuSeparatorElement: {
        prototype: HTMLVuiDropdownMenuSeparatorElement;
        new (): HTMLVuiDropdownMenuSeparatorElement;
    };
    interface HTMLVuiDropdownMenuTriggerElement extends Components.VuiDropdownMenuTrigger, HTMLStencilElement {
    }
    var HTMLVuiDropdownMenuTriggerElement: {
        prototype: HTMLVuiDropdownMenuTriggerElement;
        new (): HTMLVuiDropdownMenuTriggerElement;
    };
    interface HTMLVuiErrorMessageElement extends Components.VuiErrorMessage, HTMLStencilElement {
    }
    var HTMLVuiErrorMessageElement: {
        prototype: HTMLVuiErrorMessageElement;
        new (): HTMLVuiErrorMessageElement;
    };
    interface HTMLVuiFlexElement extends Components.VuiFlex, HTMLStencilElement {
    }
    var HTMLVuiFlexElement: {
        prototype: HTMLVuiFlexElement;
        new (): HTMLVuiFlexElement;
    };
    interface HTMLVuiFormInputElement extends Components.VuiFormInput, HTMLStencilElement {
    }
    var HTMLVuiFormInputElement: {
        prototype: HTMLVuiFormInputElement;
        new (): HTMLVuiFormInputElement;
    };
    interface HTMLVuiGoogleOneTapElementEventMap {
        "googleCredential": SignInWithIdTokenCredentials;
        "googleError": Error;
    }
    interface HTMLVuiGoogleOneTapElement extends Components.VuiGoogleOneTap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiGoogleOneTapElementEventMap>(type: K, listener: (this: HTMLVuiGoogleOneTapElement, ev: VuiGoogleOneTapCustomEvent<HTMLVuiGoogleOneTapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiGoogleOneTapElementEventMap>(type: K, listener: (this: HTMLVuiGoogleOneTapElement, ev: VuiGoogleOneTapCustomEvent<HTMLVuiGoogleOneTapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiGoogleOneTapElement: {
        prototype: HTMLVuiGoogleOneTapElement;
        new (): HTMLVuiGoogleOneTapElement;
    };
    interface HTMLVuiI18nElement extends Components.VuiI18n, HTMLStencilElement {
    }
    var HTMLVuiI18nElement: {
        prototype: HTMLVuiI18nElement;
        new (): HTMLVuiI18nElement;
    };
    interface HTMLVuiI18nProviderElementEventMap {
        "translationsLoaded": void;
    }
    interface HTMLVuiI18nProviderElement extends Components.VuiI18nProvider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiI18nProviderElementEventMap>(type: K, listener: (this: HTMLVuiI18nProviderElement, ev: VuiI18nProviderCustomEvent<HTMLVuiI18nProviderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiI18nProviderElementEventMap>(type: K, listener: (this: HTMLVuiI18nProviderElement, ev: VuiI18nProviderCustomEvent<HTMLVuiI18nProviderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiI18nProviderElement: {
        prototype: HTMLVuiI18nProviderElement;
        new (): HTMLVuiI18nProviderElement;
    };
    interface HTMLVuiIconElement extends Components.VuiIcon, HTMLStencilElement {
    }
    var HTMLVuiIconElement: {
        prototype: HTMLVuiIconElement;
        new (): HTMLVuiIconElement;
    };
    interface HTMLVuiLabelElement extends Components.VuiLabel, HTMLStencilElement {
    }
    var HTMLVuiLabelElement: {
        prototype: HTMLVuiLabelElement;
        new (): HTMLVuiLabelElement;
    };
    interface HTMLVuiLanguageSwitcherElementEventMap {
        "localeChange": string;
    }
    interface HTMLVuiLanguageSwitcherElement extends Components.VuiLanguageSwitcher, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiLanguageSwitcherElementEventMap>(type: K, listener: (this: HTMLVuiLanguageSwitcherElement, ev: VuiLanguageSwitcherCustomEvent<HTMLVuiLanguageSwitcherElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiLanguageSwitcherElementEventMap>(type: K, listener: (this: HTMLVuiLanguageSwitcherElement, ev: VuiLanguageSwitcherCustomEvent<HTMLVuiLanguageSwitcherElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiLanguageSwitcherElement: {
        prototype: HTMLVuiLanguageSwitcherElement;
        new (): HTMLVuiLanguageSwitcherElement;
    };
    interface HTMLVuiLinkElement extends Components.VuiLink, HTMLStencilElement {
    }
    var HTMLVuiLinkElement: {
        prototype: HTMLVuiLinkElement;
        new (): HTMLVuiLinkElement;
    };
    interface HTMLVuiLogoElement extends Components.VuiLogo, HTMLStencilElement {
    }
    var HTMLVuiLogoElement: {
        prototype: HTMLVuiLogoElement;
        new (): HTMLVuiLogoElement;
    };
    interface HTMLVuiOtpElementEventMap {
        "formSubmit": string;
    }
    interface HTMLVuiOtpElement extends Components.VuiOtp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiOtpElementEventMap>(type: K, listener: (this: HTMLVuiOtpElement, ev: VuiOtpCustomEvent<HTMLVuiOtpElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiOtpElementEventMap>(type: K, listener: (this: HTMLVuiOtpElement, ev: VuiOtpCustomEvent<HTMLVuiOtpElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiOtpElement: {
        prototype: HTMLVuiOtpElement;
        new (): HTMLVuiOtpElement;
    };
    interface HTMLVuiPlaceholderElement extends Components.VuiPlaceholder, HTMLStencilElement {
    }
    var HTMLVuiPlaceholderElement: {
        prototype: HTMLVuiPlaceholderElement;
        new (): HTMLVuiPlaceholderElement;
    };
    interface HTMLVuiRequestElementEventMap {
        "requestApprove": void;
        "requestDeny": void;
    }
    interface HTMLVuiRequestElement extends Components.VuiRequest, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiRequestElementEventMap>(type: K, listener: (this: HTMLVuiRequestElement, ev: VuiRequestCustomEvent<HTMLVuiRequestElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiRequestElementEventMap>(type: K, listener: (this: HTMLVuiRequestElement, ev: VuiRequestCustomEvent<HTMLVuiRequestElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiRequestElement: {
        prototype: HTMLVuiRequestElement;
        new (): HTMLVuiRequestElement;
    };
    interface HTMLVuiSpinnerElement extends Components.VuiSpinner, HTMLStencilElement {
    }
    var HTMLVuiSpinnerElement: {
        prototype: HTMLVuiSpinnerElement;
        new (): HTMLVuiSpinnerElement;
    };
    interface HTMLVuiTextboxElementEventMap {
        "valueChange": string;
        "inputChange": string;
        "enterKey": void;
    }
    interface HTMLVuiTextboxElement extends Components.VuiTextbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiTextboxElementEventMap>(type: K, listener: (this: HTMLVuiTextboxElement, ev: VuiTextboxCustomEvent<HTMLVuiTextboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiTextboxElementEventMap>(type: K, listener: (this: HTMLVuiTextboxElement, ev: VuiTextboxCustomEvent<HTMLVuiTextboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiTextboxElement: {
        prototype: HTMLVuiTextboxElement;
        new (): HTMLVuiTextboxElement;
    };
    interface HTMLVuiThemeToggleElement extends Components.VuiThemeToggle, HTMLStencilElement {
    }
    var HTMLVuiThemeToggleElement: {
        prototype: HTMLVuiThemeToggleElement;
        new (): HTMLVuiThemeToggleElement;
    };
    interface HTMLVuiToastElementEventMap {
        "dismiss": string;
    }
    interface HTMLVuiToastElement extends Components.VuiToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiToastElementEventMap>(type: K, listener: (this: HTMLVuiToastElement, ev: VuiToastCustomEvent<HTMLVuiToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiToastElementEventMap>(type: K, listener: (this: HTMLVuiToastElement, ev: VuiToastCustomEvent<HTMLVuiToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiToastElement: {
        prototype: HTMLVuiToastElement;
        new (): HTMLVuiToastElement;
    };
    interface HTMLVuiUserMenuElementEventMap {
        "menuAction": MenuAction;
    }
    interface HTMLVuiUserMenuElement extends Components.VuiUserMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVuiUserMenuElementEventMap>(type: K, listener: (this: HTMLVuiUserMenuElement, ev: VuiUserMenuCustomEvent<HTMLVuiUserMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVuiUserMenuElementEventMap>(type: K, listener: (this: HTMLVuiUserMenuElement, ev: VuiUserMenuCustomEvent<HTMLVuiUserMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVuiUserMenuElement: {
        prototype: HTMLVuiUserMenuElement;
        new (): HTMLVuiUserMenuElement;
    };
    interface HTMLElementTagNameMap {
        "verite-connector": HTMLVeriteConnectorElement;
        "vui-auth-alt-card": HTMLVuiAuthAltCardElement;
        "vui-auth-card": HTMLVuiAuthCardElement;
        "vui-auth-footer": HTMLVuiAuthFooterElement;
        "vui-auth-form": HTMLVuiAuthFormElement;
        "vui-auth-header": HTMLVuiAuthHeaderElement;
        "vui-brand": HTMLVuiBrandElement;
        "vui-button": HTMLVuiButtonElement;
        "vui-card": HTMLVuiCardElement;
        "vui-card-content": HTMLVuiCardContentElement;
        "vui-card-description": HTMLVuiCardDescriptionElement;
        "vui-card-footer": HTMLVuiCardFooterElement;
        "vui-card-header": HTMLVuiCardHeaderElement;
        "vui-card-title": HTMLVuiCardTitleElement;
        "vui-divider": HTMLVuiDividerElement;
        "vui-dropdown-menu": HTMLVuiDropdownMenuElement;
        "vui-dropdown-menu-content": HTMLVuiDropdownMenuContentElement;
        "vui-dropdown-menu-item": HTMLVuiDropdownMenuItemElement;
        "vui-dropdown-menu-separator": HTMLVuiDropdownMenuSeparatorElement;
        "vui-dropdown-menu-trigger": HTMLVuiDropdownMenuTriggerElement;
        "vui-error-message": HTMLVuiErrorMessageElement;
        "vui-flex": HTMLVuiFlexElement;
        "vui-form-input": HTMLVuiFormInputElement;
        "vui-google-one-tap": HTMLVuiGoogleOneTapElement;
        "vui-i18n": HTMLVuiI18nElement;
        "vui-i18n-provider": HTMLVuiI18nProviderElement;
        "vui-icon": HTMLVuiIconElement;
        "vui-label": HTMLVuiLabelElement;
        "vui-language-switcher": HTMLVuiLanguageSwitcherElement;
        "vui-link": HTMLVuiLinkElement;
        "vui-logo": HTMLVuiLogoElement;
        "vui-otp": HTMLVuiOtpElement;
        "vui-placeholder": HTMLVuiPlaceholderElement;
        "vui-request": HTMLVuiRequestElement;
        "vui-spinner": HTMLVuiSpinnerElement;
        "vui-textbox": HTMLVuiTextboxElement;
        "vui-theme-toggle": HTMLVuiThemeToggleElement;
        "vui-toast": HTMLVuiToastElement;
        "vui-user-menu": HTMLVuiUserMenuElement;
    }
}
declare namespace LocalJSX {
    interface VeriteConnector {
        "type"?: 'signup' | 'signin';
    }
    interface VuiAuthAltCard {
        "action"?: string;
        "description"?: string;
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
        "heading"?: string;
        "prompt"?: string;
        "submitLabel"?: string;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthCard {
        "action"?: string;
        "brandLabel"?: string;
        "brandLogo"?: string;
        "description"?: string;
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
        "heading"?: string;
        "prompt"?: string;
        "submitLabel"?: string;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthFooter {
        "action"?: string;
        "brandLabel"?: string;
        "brandLogo"?: string;
        "onActionClick"?: (event: VuiAuthFooterCustomEvent<any>) => void;
        "prompt"?: string;
        "showBrand"?: boolean;
        "showDivider"?: boolean;
        "variant"?: 'default' | 'inset';
    }
    interface VuiAuthForm {
        "action"?: 'submit' | 'signup' | 'signin' | 'forgotPassword' | 'resetPassword' | 'resetLink' | 'code';
        "elements"?: Element[] | string;
        "email"?: string;
        "emailLabel"?: string;
        "emailPlaceholder"?: string;
        /**
          * Email validation options
         */
        "emailValidation"?: EmailValidationOptions | string;
        "firstName"?: string;
        "firstnameLabel"?: string;
        "firstnamePlaceholder"?: string;
        "forgotPasswordLabel"?: string;
        /**
          * Controls the loading state of the component
         */
        "isLoading"?: boolean;
        "lastName"?: string;
        "lastnameLabel"?: string;
        "lastnamePlaceholder"?: string;
        "onForgotPassword"?: (event: VuiAuthFormCustomEvent<void>) => void;
        "onFormSubmit"?: (event: VuiAuthFormCustomEvent<SignUpFormData>) => void;
        "password"?: string;
        "passwordHideLabel"?: string;
        "passwordLabel"?: string;
        "passwordPlaceholder"?: string;
        "passwordShowLabel"?: string;
        /**
          * Password validation options
         */
        "passwordValidation"?: PasswordValidationOptions;
        "phone"?: string;
        "phoneLabel"?: string;
        "phonePlaceholder"?: string;
        "styles"?: {
    link?: { [key: string]: string | number }
  };
        "submitLabel"?: string;
    }
    interface VuiAuthHeader {
        "align"?: 'start' | 'center' | 'end';
        "description"?: string;
        "heading"?: string;
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VuiBrand {
        "label"?: string;
        "logo"?: string;
    }
    interface VuiButton {
        "busy"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "name"?: string;
        "onButtonClick"?: (event: VuiButtonCustomEvent<MouseEvent>) => void;
        "size"?: 'default' | 'sm' | 'lg' | 'icon';
        "type"?: 'button' | 'submit' | 'reset';
        "value"?: string;
        "variant"?: 'default' | 'soft' | 'outline' | 'ghost' | 'destructive';
        "width"?: 'full' | 'auto';
    }
    interface VuiCard {
        "elevation"?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VuiCardContent {
    }
    interface VuiCardDescription {
        "align"?: 'start' | 'center' | 'end';
    }
    interface VuiCardFooter {
        "variant"?: 'default' | 'inset';
    }
    interface VuiCardHeader {
    }
    interface VuiCardTitle {
        "align"?: 'start' | 'center' | 'end';
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
        "weight"?: 'bold' | 'medium' | 'light';
    }
    interface VuiDivider {
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface VuiDropdownMenu {
        "position"?: 'bottom-end' | 'bottom-start' | 'top-end' | 'top-start';
    }
    interface VuiDropdownMenuContent {
    }
    interface VuiDropdownMenuItem {
        "disabled"?: boolean;
        "onItemClick"?: (event: VuiDropdownMenuItemCustomEvent<void>) => void;
    }
    interface VuiDropdownMenuSeparator {
    }
    interface VuiDropdownMenuTrigger {
    }
    interface VuiErrorMessage {
        /**
          * The error message to display
         */
        "message"?: string;
        /**
          * Whether to show the error icon
         */
        "showIcon"?: boolean;
    }
    interface VuiFlex {
        "breakpoint"?: string;
        "breakpointDirection"?: 'row' | 'column';
        "direction"?: 'row' | 'column';
        "gap"?: number;
        "grow"?: boolean;
        "items"?: 'start' | 'center' | 'end' | 'stretch' | 'baseline';
        "justify"?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
        "spaceUnit"?: number;
        "width"?: 'full' | 'auto';
        "wrap"?: 'nowrap' | 'wrap' | 'wrap-reverse';
    }
    interface VuiFormInput {
        "errorMessage"?: string;
        "htmlFor"?: string;
        "label"?: string;
    }
    interface VuiGoogleOneTap {
        "googleClientId": string;
        "onGoogleCredential"?: (event: VuiGoogleOneTapCustomEvent<SignInWithIdTokenCredentials>) => void;
        "onGoogleError"?: (event: VuiGoogleOneTapCustomEvent<Error>) => void;
    }
    interface VuiI18n {
        "params"?: Record<string, string> | string;
        "text"?: string;
    }
    interface VuiI18nProvider {
        "fallbackLocale"?: string;
        "loadTranslations"?: (locale: string) => Promise<Translation>;
        "locale"?: string;
        "onTranslationsLoaded"?: (event: VuiI18nProviderCustomEvent<void>) => void;
        "translations"?: Translation | string;
        "translationsPath"?: string;
    }
    interface VuiIcon {
        "color"?: string;
        "name": string;
        "size"?: 'xs' | 'sm' | 'md' | 'lg';
    }
    interface VuiLabel {
        "for"?: string;
        "required"?: boolean;
    }
    interface VuiLanguageSwitcher {
        "currentLocale"?: string;
        "languages"?: Language[] | string;
        "onLocaleChange"?: (event: VuiLanguageSwitcherCustomEvent<string>) => void;
        "variant"?: 'select' | 'buttons';
    }
    interface VuiLink {
        "disabled"?: boolean;
        "href"?: string;
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        "variant"?: 'default' | 'muted' | 'destructive';
    }
    interface VuiLogo {
        /**
          * The name of the logo to display
         */
        "name": LogoName;
        /**
          * The size of the logo in pixels
         */
        "size"?: number;
    }
    interface VuiOtp {
        "onFormSubmit"?: (event: VuiOtpCustomEvent<string>) => void;
        "submitLabel"?: string;
    }
    interface VuiPlaceholder {
        /**
          * Height of the placeholder in pixels
         */
        "height"?: number;
        /**
          * Border radius in pixels. Use 9999 for fully rounded
         */
        "radius"?: number;
        /**
          * Width of the placeholder in pixels
         */
        "width"?: number;
    }
    interface VuiRequest {
        "application"?: string;
        "isLoading"?: boolean;
        "onRequestApprove"?: (event: VuiRequestCustomEvent<void>) => void;
        "onRequestDeny"?: (event: VuiRequestCustomEvent<void>) => void;
        "permissions"?: string[] | string;
        "redirectUri"?: string;
        "showRedirect"?: boolean;
    }
    interface VuiSpinner {
        "color"?: string;
        "size"?: 'small' | 'medium' | 'large';
    }
    interface VuiTextbox {
        "autocomplete"?: string;
        "autocorrect"?: 'on' | 'off';
        "disabled"?: boolean;
        "focusable"?: boolean;
        "maxlength"?: number;
        "name"?: string;
        "onEnterKey"?: (event: VuiTextboxCustomEvent<void>) => void;
        "onInputChange"?: (event: VuiTextboxCustomEvent<string>) => void;
        "onValueChange"?: (event: VuiTextboxCustomEvent<string>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface VuiThemeToggle {
    }
    interface VuiToast {
        "duration"?: number;
        "gap"?: number;
        "onDismiss"?: (event: VuiToastCustomEvent<string>) => void;
        "position"?: 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
        "theme"?: 'default' | 'light' | 'dark' | 'inverted';
    }
    interface VuiUserMenu {
        "onMenuAction"?: (event: VuiUserMenuCustomEvent<MenuAction>) => void;
    }
    interface IntrinsicElements {
        "verite-connector": VeriteConnector;
        "vui-auth-alt-card": VuiAuthAltCard;
        "vui-auth-card": VuiAuthCard;
        "vui-auth-footer": VuiAuthFooter;
        "vui-auth-form": VuiAuthForm;
        "vui-auth-header": VuiAuthHeader;
        "vui-brand": VuiBrand;
        "vui-button": VuiButton;
        "vui-card": VuiCard;
        "vui-card-content": VuiCardContent;
        "vui-card-description": VuiCardDescription;
        "vui-card-footer": VuiCardFooter;
        "vui-card-header": VuiCardHeader;
        "vui-card-title": VuiCardTitle;
        "vui-divider": VuiDivider;
        "vui-dropdown-menu": VuiDropdownMenu;
        "vui-dropdown-menu-content": VuiDropdownMenuContent;
        "vui-dropdown-menu-item": VuiDropdownMenuItem;
        "vui-dropdown-menu-separator": VuiDropdownMenuSeparator;
        "vui-dropdown-menu-trigger": VuiDropdownMenuTrigger;
        "vui-error-message": VuiErrorMessage;
        "vui-flex": VuiFlex;
        "vui-form-input": VuiFormInput;
        "vui-google-one-tap": VuiGoogleOneTap;
        "vui-i18n": VuiI18n;
        "vui-i18n-provider": VuiI18nProvider;
        "vui-icon": VuiIcon;
        "vui-label": VuiLabel;
        "vui-language-switcher": VuiLanguageSwitcher;
        "vui-link": VuiLink;
        "vui-logo": VuiLogo;
        "vui-otp": VuiOtp;
        "vui-placeholder": VuiPlaceholder;
        "vui-request": VuiRequest;
        "vui-spinner": VuiSpinner;
        "vui-textbox": VuiTextbox;
        "vui-theme-toggle": VuiThemeToggle;
        "vui-toast": VuiToast;
        "vui-user-menu": VuiUserMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "verite-connector": LocalJSX.VeriteConnector & JSXBase.HTMLAttributes<HTMLVeriteConnectorElement>;
            "vui-auth-alt-card": LocalJSX.VuiAuthAltCard & JSXBase.HTMLAttributes<HTMLVuiAuthAltCardElement>;
            "vui-auth-card": LocalJSX.VuiAuthCard & JSXBase.HTMLAttributes<HTMLVuiAuthCardElement>;
            "vui-auth-footer": LocalJSX.VuiAuthFooter & JSXBase.HTMLAttributes<HTMLVuiAuthFooterElement>;
            "vui-auth-form": LocalJSX.VuiAuthForm & JSXBase.HTMLAttributes<HTMLVuiAuthFormElement>;
            "vui-auth-header": LocalJSX.VuiAuthHeader & JSXBase.HTMLAttributes<HTMLVuiAuthHeaderElement>;
            "vui-brand": LocalJSX.VuiBrand & JSXBase.HTMLAttributes<HTMLVuiBrandElement>;
            "vui-button": LocalJSX.VuiButton & JSXBase.HTMLAttributes<HTMLVuiButtonElement>;
            "vui-card": LocalJSX.VuiCard & JSXBase.HTMLAttributes<HTMLVuiCardElement>;
            "vui-card-content": LocalJSX.VuiCardContent & JSXBase.HTMLAttributes<HTMLVuiCardContentElement>;
            "vui-card-description": LocalJSX.VuiCardDescription & JSXBase.HTMLAttributes<HTMLVuiCardDescriptionElement>;
            "vui-card-footer": LocalJSX.VuiCardFooter & JSXBase.HTMLAttributes<HTMLVuiCardFooterElement>;
            "vui-card-header": LocalJSX.VuiCardHeader & JSXBase.HTMLAttributes<HTMLVuiCardHeaderElement>;
            "vui-card-title": LocalJSX.VuiCardTitle & JSXBase.HTMLAttributes<HTMLVuiCardTitleElement>;
            "vui-divider": LocalJSX.VuiDivider & JSXBase.HTMLAttributes<HTMLVuiDividerElement>;
            "vui-dropdown-menu": LocalJSX.VuiDropdownMenu & JSXBase.HTMLAttributes<HTMLVuiDropdownMenuElement>;
            "vui-dropdown-menu-content": LocalJSX.VuiDropdownMenuContent & JSXBase.HTMLAttributes<HTMLVuiDropdownMenuContentElement>;
            "vui-dropdown-menu-item": LocalJSX.VuiDropdownMenuItem & JSXBase.HTMLAttributes<HTMLVuiDropdownMenuItemElement>;
            "vui-dropdown-menu-separator": LocalJSX.VuiDropdownMenuSeparator & JSXBase.HTMLAttributes<HTMLVuiDropdownMenuSeparatorElement>;
            "vui-dropdown-menu-trigger": LocalJSX.VuiDropdownMenuTrigger & JSXBase.HTMLAttributes<HTMLVuiDropdownMenuTriggerElement>;
            "vui-error-message": LocalJSX.VuiErrorMessage & JSXBase.HTMLAttributes<HTMLVuiErrorMessageElement>;
            "vui-flex": LocalJSX.VuiFlex & JSXBase.HTMLAttributes<HTMLVuiFlexElement>;
            "vui-form-input": LocalJSX.VuiFormInput & JSXBase.HTMLAttributes<HTMLVuiFormInputElement>;
            "vui-google-one-tap": LocalJSX.VuiGoogleOneTap & JSXBase.HTMLAttributes<HTMLVuiGoogleOneTapElement>;
            "vui-i18n": LocalJSX.VuiI18n & JSXBase.HTMLAttributes<HTMLVuiI18nElement>;
            "vui-i18n-provider": LocalJSX.VuiI18nProvider & JSXBase.HTMLAttributes<HTMLVuiI18nProviderElement>;
            "vui-icon": LocalJSX.VuiIcon & JSXBase.HTMLAttributes<HTMLVuiIconElement>;
            "vui-label": LocalJSX.VuiLabel & JSXBase.HTMLAttributes<HTMLVuiLabelElement>;
            "vui-language-switcher": LocalJSX.VuiLanguageSwitcher & JSXBase.HTMLAttributes<HTMLVuiLanguageSwitcherElement>;
            "vui-link": LocalJSX.VuiLink & JSXBase.HTMLAttributes<HTMLVuiLinkElement>;
            "vui-logo": LocalJSX.VuiLogo & JSXBase.HTMLAttributes<HTMLVuiLogoElement>;
            "vui-otp": LocalJSX.VuiOtp & JSXBase.HTMLAttributes<HTMLVuiOtpElement>;
            "vui-placeholder": LocalJSX.VuiPlaceholder & JSXBase.HTMLAttributes<HTMLVuiPlaceholderElement>;
            "vui-request": LocalJSX.VuiRequest & JSXBase.HTMLAttributes<HTMLVuiRequestElement>;
            "vui-spinner": LocalJSX.VuiSpinner & JSXBase.HTMLAttributes<HTMLVuiSpinnerElement>;
            "vui-textbox": LocalJSX.VuiTextbox & JSXBase.HTMLAttributes<HTMLVuiTextboxElement>;
            "vui-theme-toggle": LocalJSX.VuiThemeToggle & JSXBase.HTMLAttributes<HTMLVuiThemeToggleElement>;
            "vui-toast": LocalJSX.VuiToast & JSXBase.HTMLAttributes<HTMLVuiToastElement>;
            "vui-user-menu": LocalJSX.VuiUserMenu & JSXBase.HTMLAttributes<HTMLVuiUserMenuElement>;
        }
    }
}
